//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxGames_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarritoCompra
    {
        public int ID_CarritoCompra { get; set; }
        public int ID_Cliente { get; set; }
        public string ID_JuegoMesa { get; set; }
        public Nullable<int> Precio { get; set; }
    }
}
