//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxGames_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class JuegosMesa
    {
        public int ID_JuegoMesa { get; set; }
        public string NombreJuego { get; set; }
        public string TipoJuego { get; set; }
        public int PrecioJuego { get; set; }
        public string DescripcionJuego { get; set; }
        public string ImagenJuego { get; set; }
        public int CantidadJuego { get; set; }
    }
}
